"""create initial CrimeAlert schema

Revision ID: 62e25f082375
Revises: 
Create Date: 2026-08-28 17:00:09.186947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e25f082375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('crime_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('crime_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('risk_level', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('high', 'medium', 'low')", name='ck_crime_reports_risk_level'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_crime_reports_status'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_crime_reports_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_crime_reports_longitude_range'),
    sa.ForeignKeyConstraint(['crime_type'], ['crime_types.name'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crime_reports', schema=None) as batch_op:
        batch_op.create_index('ix_crime_reports_crime_type', ['crime_type'], unique=False)
        batch_op.create_index('ix_crime_reports_incident_datetime', ['incident_datetime'], unique=False)
        batch_op.create_index('ix_crime_reports_latitude_longitude', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index('ix_crime_reports_risk_level', ['risk_level'], unique=False)
        batch_op.create_index('ix_crime_reports_status', ['status'], unique=False)

    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_report_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_report_id'], ['crime_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_target_report_id'), ['target_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['crime_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_report_id'), ['report_id'], unique=False)

    op.create_table('report_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IN ('image', 'video')", name='ck_report_media_media_type'),
    sa.ForeignKeyConstraint(['report_id'], ['crime_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_media_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_media_report_id'))

    op.drop_table('report_media')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_report_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('admin_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_target_report_id'))
        batch_op.drop_index(batch_op.f('ix_admin_logs_admin_id'))

    op.drop_table('admin_logs')
    with op.batch_alter_table('crime_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_crime_reports_status')
        batch_op.drop_index('ix_crime_reports_risk_level')
        batch_op.drop_index(batch_op.f('ix_crime_reports_reporter_id'))
        batch_op.drop_index('ix_crime_reports_latitude_longitude')
        batch_op.drop_index('ix_crime_reports_incident_datetime')
        batch_op.drop_index('ix_crime_reports_crime_type')

    op.drop_table('crime_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('emergency_contacts')
    op.drop_table('crime_types')
    # ### end Alembic commands ###
